name: Daily LeetCode Streak

on:
  schedule:
    - cron: "30 3 * * *"  # Runs daily at 9:00 AM IST
  workflow_dispatch:  # allows manual run

jobs:
  send-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests twilio

      - name: Run script
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
        run: python streak.py
